### ISSUE TITLE
blurry segmentation and low res masks

### ISSUE THREAD

**Issue by grace-fengqing-yu** [uni-medical/SAM-Med3D#27]
Hi, very exciting work!! I tried to use this model on my 3D microscopy image dataset, with the shape of (128,128,128). However, when I visualized the results I saw that the predictions were often very blurry. I realized that in the code you downsampled the mask size from (128, 128, 128) to (32, 32, 32) and then upsampled the predictions via interpolation. Am I missing something or is this essentially processing the image with resolution (32, 32, 32)? And if yes are there some ways I can maintain the resolution of the prediction as my input (128, 128, 128)? Thank you!

For reference, these are some of the images I had, where left is the input and right is the prediction.
<img width="511" alt="image" src="https://github.com/uni-medical/SAM-Med3D/assets/90643724/e6087d3a-3a9c-484c-8d0e-4e3f0018d36d">
<img width="491" alt="image" src="https://github.com/uni-medical/SAM-Med3D/assets/90643724/97fae771-ce13-4310-9ff1-8e808ea91c58">

**Comment by blueyo0** [comment]
Hi, grace, thank you for your recognition first~

Don't worry about the upsample/downsample operation for now, as it is similar to SAM, designed to provide low-resolution mask prompts to enhance segmentation accuracy. 

Regarding your issue, I believe the key problem lies in the blurry prediction, which is abnormal because the line of code `medsam_seg = (medsam_seg_prob > 0.5).astype(np.uint8)` ensures the output is in uint8. Perhaps your visualization code involved some inappropriate resizing, or you customized a new saving process? I suggest you provide more details (specific output and visualization code used) and your test cases so that I can reproduce your issue. 

hope my answer helps you.
