### ISSUE TITLE
possibility for multiclass semantic segmentation

### ISSUE THREAD

**Issue by ramdhan1989** [uni-medical/SAM-Med3D#34]
Hi,
I would like to ask if the code is easily to be modified for multiclass semantic segmentation? 

please advise,

thanks

**Comment by blueyo0** [comment]
I think it is easy. You only need to change the seg head of the model to support multi-class seg and modify the training pipeline.

However, I don't suggest you to do som because this code is only experimental code for research of promptable seg.
A better way is to modify a SOTA multi-class semantic seg code (e.g. STU-Net，nnU-Net), and then you only need to change the model. 

Hope this can help you.

**Comment by SergioRodLla** [comment]
Hi @blueyo0 ,

I am trying to do exactly that, I want to try to finetune the SAM-Med3D model in the nnUNet framework (v2). I am a beginner at this and I was wondering if you could tell me which are the key parts that I should introduce to finetune one of the checkpoints (e.g. SAM-Med3D-turbo).
Thank you.

Best,
Sergio

**Comment by blueyo0** [comment]
Hi, currently, SAM-Med3D only supports single-modal inputs. If you expect to support promptable seg pipeline in nnUNet, you may need to implement your own trainer and the related inference functions.
