### ISSUE TITLE
【train】【performance】about the fine tune result

### ISSUE THREAD

**Issue by SillyPigeon** [uni-medical/SAM-Med3D#61]
Hi 
Thanks for your great jobs. However, when I try to fine tune dataset in my vessels data(for train 200+epochs in imageCAS dataset). 
The inference result was so bad that it could not be used in project. Do you have some ideas about this?
<img width="421" alt="image" src="https://github.com/uni-medical/SAM-Med3D/assets/19251255/6aa9ee83-72d0-4e0c-ad12-21b43f93e5fa">
the main picture is GT
<img width="567" alt="image" src="https://github.com/uni-medical/SAM-Med3D/assets/19251255/6cf91ec0-b15d-482d-9ead-a0a2e6894d50">

**Comment by blueyo0** [comment]
Hi, Coronary Artery is a challenging target, and I suggest you adjust the window size (instead of `128`, you can use a larger window to make sure the artery is continuous) and spacing of the data (instead of `1.5`, maybe using sparse slices with high-resolution images `3x0.8x0.8` is better?). Anyway, specific modification of data processing seems help for your task. Thx.
