### ISSUE TITLE
patch-based inference approach for 3D volumes

### ISSUE THREAD

**Issue by himashi92** [uni-medical/SAM-Med3D#7]
Hi,

Thanks for sharing your work with the community. Excellent work!

I have successfully trained SAM-Med3D for the brain tumor dataset, and now I want to evaluate the test set. In the paper, it is mentioned that SAM-Med3D operates using a patch-based inference approach. However, in the repository, I needed help finding the script or suitable function you used for 3D patch-based inference. I would appreciate it if you could share the script for this or let me know if I missed something here. :)

Kind regards,
Himashi

**Comment by hagersalehahmed** [comment]
how can solve this problem  File 
 line 343, in train_epoch
    epoch_loss /= step
ZeroDivisionError: float division by zero

**Comment by blueyo0** [comment]
> Hi,
> 
> Thanks for sharing your work with the community. Excellent work!
> 
> I have successfully trained SAM-Med3D for the brain tumor dataset, and now I want to evaluate the test set. In the paper, it is mentioned that SAM-Med3D operates using a patch-based inference approach. However, in the repository, I needed help finding the script or suitable function you used for 3D patch-based inference. I would appreciate it if you could share the script for this or let me know if I missed something here. :)
> 
> Kind regards, Himashi

Hi, Himashi, thank you for your recognition~

Our patch-based inference script is the `validation.py`, and you can refer to [evaluation in Readme](https://github.com/uni-medical/SAM-Med3D#evaluation) for usage. BTW, this script only supports inference on a single patch (crop from the center of the target) instead of sliding-window inference of the whole image. If you need to conduct sliding-window inference, you may need to modify the script yourself or wait for my further update.

**Comment by blueyo0** [comment]
> how can solve this problem File line 343, in train_epoch epoch_loss /= step ZeroDivisionError: float division by zero

Hi, hagersalehahmed
It seems like this issue is raised because your dataset is empty, so no step is run (step=0).
Please check your data first, example data structure in [training](https://github.com/uni-medical/SAM-Med3D#training) may be helpful.
