### ISSUE TITLE
Muti-class segmentation

### ISSUE THREAD

**Issue by 1774537072** [uni-medical/SAM-Med3D#91]
Thank you for sharing your great work!

Have you tried using SAM-Med3D for multi-class segmentation, such as multi-organ segmentation or something like it?

I'm trying to do it using BraT20 dataset for Brain Tumor Segentation, but it seems like SAM-Med3D is easily influenced by the background class. Specifically, the first class of the mask tokens in the mask-decoder is significantly large.

Do you have any clue about this problem?

**Comment by blueyo0** [comment]
Hi, since SAM-Med3D doesn't actually support multi-class seg. Plz clarify your setting. For example, do you use it multiple times with different prompt points to get different output the multiple organs?

BTW, since BraTS is tumor seg dataset, where the target is relatively small, it's reasonable that it is refluenced by the background class.

**Comment by 1774537072** [comment]
I only use one point in your source code as the input of the Prompt Encoder, and modify four MLPs. Specifically, I replace the output_hypernetworks_mlps in the Mask Decoder with new MLPs, so that the four masks output by the Mask Decoder correspond to the masks of four different classes.

**Comment by blueyo0** [comment]
It seems that you made structural modifications and then conducted experiments under the changed settings. Since I haven't conducted this kind of experiment, I'm afraid I won't be able to give useful suggestions. If you want a detailed discussion, you can present specific results or start a discussion for this repository. Or you can just close this issue. Thx.

**Comment by yyang1063** [comment]
可以一起讨论一下吗 @1774537072
